### ISSUE TITLE
Can't Find saved files 

### ISSUE THREAD

**Issue by mrk3260** [U7P4L-IN/FB-TOOLSBOX#3]
I can't find whrer the EMRAN-ok.txt file saved .

![73562B5C-F15A-4D83-8E6B-EC44C65E1D67](https://github.com/U7P4L-IN/FB-TOOLSBOX/assets/125546974/59c5c5a7-6701-4fb2-89b8-e0c7f8683467)

there not saved in termux /CHILL file

**Comment by U7P4L-IN** [comment]
sry this repository is updating
